plugins = []
functionsDirectory = "/home/z/my-project/netlify-log-probe/functions"
functionsDirectoryOrigin = "config-v1"
headers = []
redirects = []

[functions]

[functions."*"]
included_files = ["functions/node_modules/**"]
external_node_modules = ["tls-impersonate"]
node_bundler = "zisi"

[build]
publish = "/home/z/my-project/netlify-log-probe/src"
publishOrigin = "config"
commandOrigin = "config"
base = "/home/z/my-project/netlify-log-probe"
command = "npm install"
functions = "/home/z/my-project/netlify-log-probe/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]