headers = []
redirects = []

[functions]

[functions."*"]

[[plugins]]
origin = "config"
package = "./plugins/store-data"

[plugins.inputs]

[build]
publish = "/home/z/my-project/netlify-log-probe/src"
publishOrigin = "config"
commandOrigin = "config"
base = "/home/z/my-project/netlify-log-probe"
command = "node src/scrape.js"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]