functionsDirectory = "/home/z/my-project/netlify-log-probe/functions"
functionsDirectoryOrigin = "config-v1"
headers = []
redirects = []

[functions]

[functions.scrape-af]
schedule = "*/5 * * * *"

[functions."*"]
node_bundler = "esbuild"

[[plugins]]
origin = "config"
package = "./plugins/probe-build"

[plugins.inputs]

[build]
publish = "/home/z/my-project/netlify-log-probe/src"
publishOrigin = "config"
commandOrigin = "config"
base = "/home/z/my-project/netlify-log-probe"
command = "node src/build-log-probe.js"
functions = "/home/z/my-project/netlify-log-probe/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]